apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: docker.io/some-image:1.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-configmap