apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: docker.io/some-image:1.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-configmap
          livenessProbe: # checa se a aplicação esta saudável
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe: # checa se a aplicação esta pronta para responder
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources: # config para hpa
            requests:
              cpu: 10m