apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-cms-statefulset
spec:
  replicas: 1
    selector:
    matchLabels:
      app: app-cms
  template:
    metadata:
      name: app-cms
      labels:
        app: app-cms
    spec:
      containers:
        - name: app-cms-container
          image: docker.io/some-image:1.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-cms-configmap 
          volumeMounts:
            - name: storage
            mountPath: /storage
          livenessProbe: # checa se a aplicação esta saudável
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe: # checa se a aplicação esta pronta para responder
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage-pvc
  selector:
    matchLabels:
      app: app-cms
  serviceName: svc-app-cms