apiVersion: v1
kind: Pod
metadata:
  name: app-db
  labels: 
    app: app-db
spec:
  containers:
    - name: app-db-container
      image: docker.io/some-db-image:1.0
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: app-db-configmap